# Generated by Django 2.2.19 on 2021-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество объявлений'),
        ),
    ]
