# Generated by Django 2.2.19 on 2021-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='count',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Количество объявлений'),
        ),
    ]
