# Generated by Django 2.2.19 on 2021-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211208_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество объявлений'),
        ),
    ]
