# Generated by Django 2.2.19 on 2021-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211208_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество объявлений'),
        ),
    ]
