# Generated by Django 2.2.19 on 2021-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211208_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='count',
        ),
    ]
