# Generated by Django 2.2.19 on 2021-12-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211208_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveads',
            options={'verbose_name': 'Архивное объявление', 'verbose_name_plural': 'Архивные объявления'},
        ),
    ]
